# Generated by Django 4.0.2 on 2022-02-14 17:43

from django.db import migrations, models
import workshop.helpers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[workshop.helpers.validators.validate_min_year, workshop.helpers.validators.validate_max_year]),
        ),
    ]
