# Generated by Django 4.0.2 on 2022-02-13 12:19

from django.db import migrations, models
import workshop.helpers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[workshop.helpers.validators.validate_min_year, workshop.helpers.validators.validate_max_year]),
        ),
    ]
