# Generated by Django 4.0.2 on 2022-02-12 12:46

from django.db import migrations, models
import workshop.helpers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(upload_to='', validators=[workshop.helpers.validators.validate_file_size]),
        ),
    ]
