# Generated by Django 4.0.2 on 2022-02-13 12:19

from django.db import migrations, models
import workshop.helpers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images', validators=[workshop.helpers.validators.validate_file_size]),
        ),
    ]
